### ISSUE TITLE
Better description / examples in README

### ISSUE THREAD

**Issue by fzakaria** [letsencrypt/pkcs11key#17]
Hello,

I'm trying to figure out if I can use this package for use with go's SSH + my yubikey.

I was wondering if you could provide a sample in the README on how best to setup the key so that I could make use of the Signer.

**Comment by jsha** [comment]
I bet you can! Follow the instructions at https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html to get your Yubikey set up in PIV mode. Once you've done that, you should be able to feed the relevant pieces into a `pkcs11key`. If you'd like to add such details in the README I would welcome a PR!

**Comment by fzakaria** [comment]
I guess I'm curious what OpenSSH with the PKCS#11 provider does that requires it not to need the following: tokenLabel & publicKey. It seems to just prompt for the PIN...

Equivalent to something like:

```
func New(modulePath, getPin func() (string, error) ) (*Key, error) {
 ....
}
```

**Comment by jsha** [comment]
PKCS#11 tokens can make certain objects available without logging in, in particular public keys and/or certificates. I *believe* OpenSSH scans all available tokens in all available slots for public keys (or certificates), and offers them to the server. If the server says "yes, I'd accept that public key," OpenSSH prompts for the PIN to login and gain access to the private key.

**Comment by jsha** [comment]
I'm open to more specific suggestions on improving the language. For now I'm going to close this. Thanks for filing!
