### ISSUE TITLE
Cards with ALWAYS_AUTHENTICATE not working as intended wih latest opensc

### ISSUE THREAD

**Issue by Albibek** [letsencrypt/pkcs11key#19]
Hi. 
Whil using this library I've found the bug with the updated opensc(0.18) giving me CKR_USER_NOT_LOGGED_IN when signing certifiacte using Yubikey 4. This card has ALWAYS_AUTHENTICATE turned on for private keys, so it fails because of new fixes in openSC. The upstream bug is described [here](https://github.com/OpenSC/OpenSC/issues/1269). 
 
I've also found a way to fix this like it said in comments: adding a CKU_CONTEXT_SPECIFIC login after init stage. 
Example
```
	// Perform the sign operation
	err = ps.module.SignInit(*ps.session, mechanism, ps.privateKeyHandle)
	if err != nil {
		return nil, fmt.Errorf("pkcs11key: sign init: %s", err)
	}
// ADDITION_BEGIN
	if err = ps.module.Login(*ps.session, pkcs11.CKU_CONTEXT_SPECIFIC, ps.pin); err != nil {
		return nil, fmt.Errorf("pkcs11key: context-specific login: %s", err)
	}
// ADDITION_END
	signature, err = ps.module.Sign(*ps.session, signatureInput)
	if err != nil {
		return nil, fmt.Errorf("pkcs11key: sign: %s", err)
	}

```

Sorry for not making a PR, since I'm not sure I'm able to get one of appropriate quality. Still hoping this will save some deep digging if someone exept me meets this problem.

**Comment by jsha** [comment]
Thanks for sharing! I'm afraid I don't have the time right now to dig into the details and figure out what the best fix is, but hopefully this will be helpful for people in the meantime!

**Comment by frankmorgner** [comment]
See https://github.com/letsencrypt/pkcs11key/pull/24 for a fix

**Comment by jsha** [comment]
@Albibek can you confirm that the latest version works for you?

**Comment by Albibek** [comment]
Sorry for the delay. This works now, thank you.
