### ISSUE TITLE
v2.0.0 is Go Module +incompatible

### ISSUE THREAD

**Issue by gdbelvin** [letsencrypt/pkcs11key#22]
When go module enabled projects depend on `pkcs11key`, the dependencies are marked as go module `+incompatible`:

`github.com/letsencrypt/pkcs11key v2.0.1-0.20170608213348-396559074696+incompatible`

This is because, in go modules expectes packages that have >v2 to have semantic import versioning: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by jsha** [comment]
What's the suggested fix here? Will adding a go.mod make go modules treat this correctly?

**Comment by gdbelvin** [comment]
There are two potential resolutions to this issue:
- Replace v2.0 with v1.1.0
- Add a /v2/ to the import path for code in the v2.* releases.

**Comment by jsha** [comment]
> Replace v2.0 with v1.1.0

This would break the Go compatibility guidelines, since v1.0 to v2.0 was a breaking change.

> Add a /v2/ to the import path for code in the v2.* releases.

I think this is the right change, but it needs to be made by code that imports pkcs11key. Do you think I should update the README to mention the suggested import path?

**Comment by gdbelvin** [comment]
Creating the /v2/ import path would be great.
If you'd like to maintain backwards compatibility to the original path, go
supports type aliasing, but that would defeat the purpose of having a
separate path for v1.
